//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ \.
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:         BSD License
//                   Kratos default license: kratos/license.txt
//
//  Main authors:    Pooyan Dadvand
//

#if !defined(KRATOS_VARIABLES_H_INCLUDED )
#define  KRATOS_VARIABLES_H_INCLUDED

// System includes
#include <string>
#include <iostream>

// External includes

// Project includes
#include "includes/define.h"
#include "containers/variable.h"
#include "containers/variable_component.h"
#include "containers/vector_component_adaptor.h"
#include "includes/kratos_components.h"
#include "includes/ublas_interface.h"
#include "containers/array_1d.h"
#include "containers/weak_pointer_vector.h"
#include "containers/periodic_variables_container.h"

#undef  KRATOS_EXPORT_MACRO
#define KRATOS_EXPORT_MACRO KRATOS_API

namespace Kratos
{
    //Define Variables by type:

    //bools
    KRATOS_DEFINE_VARIABLE(bool, IS_RESTARTED )
    KRATOS_DEFINE_VARIABLE(bool, COMPUTE_DYNAMIC_TANGENT )
    KRATOS_DEFINE_VARIABLE(bool, COMPUTE_LUMPED_MASS_MATRIX )

    //ints
    KRATOS_DEFINE_VARIABLE( int, DOMAIN_SIZE )

    //for General kratos application:
    KRATOS_DEFINE_VARIABLE( int, LOAD_RESTART )
    KRATOS_DEFINE_VARIABLE( int, TIME_STEPS )
    KRATOS_DEFINE_VARIABLE( int, RIGID_BODY_ID )

    //for Structural application
    KRATOS_DEFINE_VARIABLE( int, FIRST_TIME_STEP )
    KRATOS_DEFINE_VARIABLE( int, QUASI_STATIC_ANALYSIS )


    KRATOS_DEFINE_VARIABLE( int, NL_ITERATION_NUMBER )
    KRATOS_DEFINE_VARIABLE( int, PERIODIC_PAIR_INDEX )
    KRATOS_DEFINE_VARIABLE( int, STATIONARY )
    KRATOS_DEFINE_VARIABLE( int, ACTIVATION_LEVEL )

    KRATOS_DEFINE_VARIABLE( int, PARTITION_MASK )

    //for PFEM fluids application:
    KRATOS_DEFINE_VARIABLE( int, SCALE )

    //for Level Set application:
    KRATOS_DEFINE_VARIABLE( int, REFINEMENT_LEVEL )

    KRATOS_DEFINE_VARIABLE( int, STEP )

    //doubles

    //for General kratos application:
    KRATOS_DEFINE_DOUBLE_VARIABLE( TIME )
    KRATOS_DEFINE_DOUBLE_VARIABLE( START_TIME )
    KRATOS_DEFINE_DOUBLE_VARIABLE( END_TIME )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DELTA_TIME )

    KRATOS_DEFINE_DOUBLE_VARIABLE( RESIDUAL_NORM )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CONVERGENCE_RATIO )

    KRATOS_DEFINE_DOUBLE_VARIABLE( TEMPERATURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PRESSURE )

    KRATOS_DEFINE_DOUBLE_VARIABLE( NEGATIVE_FACE_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( POSITIVE_FACE_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( FACE_HEAT_FLUX )

    KRATOS_DEFINE_DOUBLE_VARIABLE( DENSITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YOUNG_MODULUS )
    KRATOS_DEFINE_DOUBLE_VARIABLE( POISSON_RATIO )
    KRATOS_DEFINE_DOUBLE_VARIABLE( THICKNESS )

    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_H )

    KRATOS_DEFINE_DOUBLE_VARIABLE( KINETIC_ENERGY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( INTERNAL_ENERGY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( STRAIN_ENERGY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( EXTERNAL_ENERGY )

    KRATOS_DEFINE_DOUBLE_VARIABLE( STABILIZATION_FACTOR )

    KRATOS_DEFINE_DOUBLE_VARIABLE( TIME_INTEGRATION_THETA )

    //scheme info :: pass to elements
    KRATOS_DEFINE_DOUBLE_VARIABLE( NEWMARK_BETA )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NEWMARK_GAMMA )
    KRATOS_DEFINE_DOUBLE_VARIABLE( BOSSAK_ALPHA )
    KRATOS_DEFINE_DOUBLE_VARIABLE( EQUILIBRIUM_POINT )

    //for Structural application
    KRATOS_DEFINE_DOUBLE_VARIABLE( FRICTION_COEFFICIENT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( LAMBDA )
    KRATOS_DEFINE_DOUBLE_VARIABLE( MIU )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NORMAL_CONTACT_STRESS )
    KRATOS_DEFINE_DOUBLE_VARIABLE( TANGENTIAL_CONTACT_STRESS )

    KRATOS_DEFINE_VARIABLE( int, PARTITION_INDEX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( TEMPERATURE_OLD_IT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( VISCOSITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ERROR_RATIO )
    KRATOS_DEFINE_DOUBLE_VARIABLE( RHS_WATER )
    KRATOS_DEFINE_DOUBLE_VARIABLE( RHS_AIR )
    KRATOS_DEFINE_DOUBLE_VARIABLE( WEIGHT_FATHER_NODES )
    KRATOS_DEFINE_DOUBLE_VARIABLE( INITIAL_PENALTY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DP_EPSILON )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DP_ALPHA1 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DP_K )
    KRATOS_DEFINE_DOUBLE_VARIABLE( INTERNAL_FRICTION_ANGLE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( K0 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_VOLUME )

    KRATOS_DEFINE_DOUBLE_VARIABLE( WATER_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( REACTION_WATER_PRESSURE )

    KRATOS_DEFINE_DOUBLE_VARIABLE( AIR_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( REACTION_AIR_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( FLAG_VARIABLE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DISTANCE )

    KRATOS_DEFINE_DOUBLE_VARIABLE( LAGRANGE_AIR_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( LAGRANGE_WATER_PRESSURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( LAGRANGE_TEMPERATURE )

    //ALEApplication
    KRATOS_DEFINE_DOUBLE_VARIABLE( AUX_MESH_VAR )

    //for MultiScale application
    KRATOS_DEFINE_VARIABLE( Vector, INITIAL_STRAIN )
    KRATOS_DEFINE_DOUBLE_VARIABLE( COEFFICIENT_THERMAL_EXPANSION )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CHARACTERISTIC_LENGTH_MULTIPLIER )

    //AdjointFluidApplication
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VELOCITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ADJOINT_PRESSURE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( PRIMAL_VELOCITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PRIMAL_PRESSURE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( SHAPE_SENSITIVITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NORMAL_SENSITIVITY )

    //for PFEM fluids application:
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_AREA )

    KRATOS_DEFINE_DOUBLE_VARIABLE( BULK_MODULUS )
    KRATOS_DEFINE_DOUBLE_VARIABLE( SATURATION )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DENSITY_WATER )
    KRATOS_DEFINE_DOUBLE_VARIABLE( VISCOSITY_WATER )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DENSITY_AIR )
    KRATOS_DEFINE_DOUBLE_VARIABLE( VISCOSITY_AIR )
    KRATOS_DEFINE_DOUBLE_VARIABLE( POROSITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( DIAMETER )
    KRATOS_DEFINE_DOUBLE_VARIABLE( LIN_DARCY_COEF )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NONLIN_DARCY_COEF )

    KRATOS_DEFINE_DOUBLE_VARIABLE( AIR_ENTRY_VALUE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( FIRST_SATURATION_PARAM )
    KRATOS_DEFINE_DOUBLE_VARIABLE( SECOND_SATURATION_PARAM )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PERMEABILITY_WATER )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PERMEABILITY_AIR )
    KRATOS_DEFINE_DOUBLE_VARIABLE( BULK_AIR )

    KRATOS_DEFINE_DOUBLE_VARIABLE( TEMP_CONV_PROJ )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CONVECTION_COEFFICIENT )

    KRATOS_DEFINE_DOUBLE_VARIABLE( SOUND_VELOCITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( AIR_SOUND_VELOCITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( WATER_SOUND_VELOCITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_MASS )
    KRATOS_DEFINE_DOUBLE_VARIABLE( AUX_INDEX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( VELOCITY_PERIOD )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ANGULAR_VELOCITY_PERIOD )
    KRATOS_DEFINE_VARIABLE( std::string, IDENTIFIER )

    //for Other applications:
    KRATOS_DEFINE_DOUBLE_VARIABLE( ARRHENIUS )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ARRHENIUSAUX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ARRHENIUSAUX_ )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PRESSUREAUX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_MAUX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_PAUX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( HEAT_FLUX )
    KRATOS_DEFINE_DOUBLE_VARIABLE( TC )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CONDUCTIVITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( SPECIFIC_HEAT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( MATERIAL_VARIABLE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( FUEL )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YO )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YF )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YI )
    KRATOS_DEFINE_DOUBLE_VARIABLE( Y1 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( Y2 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YP )

    KRATOS_DEFINE_DOUBLE_VARIABLE( ABSORPTION_COEFFICIENT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( STEFAN_BOLTZMANN_CONSTANT )

    KRATOS_DEFINE_DOUBLE_VARIABLE( EXTERNAL_PRESSURE )

    KRATOS_DEFINE_DOUBLE_VARIABLE( EMISSIVITY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ENTHALPY )
    KRATOS_DEFINE_DOUBLE_VARIABLE( MIXTURE_FRACTION )


    KRATOS_DEFINE_DOUBLE_VARIABLE( YCH4 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YO2 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YCO2 )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YH2O )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YN2 )

    KRATOS_DEFINE_DOUBLE_VARIABLE( WET_VOLUME )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CUTTED_AREA )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NET_INPUT_MATERIAL )

    KRATOS_DEFINE_DOUBLE_VARIABLE( INCIDENT_RADIATION_FUNCTION )

    KRATOS_DEFINE_DOUBLE_VARIABLE( SWITCH_TEMPERATURE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( NODAL_SWITCH )

    //for Xfem application:
    KRATOS_DEFINE_DOUBLE_VARIABLE( CRACK_OPENING )
    KRATOS_DEFINE_DOUBLE_VARIABLE( CRACK_TRANSLATION )

    //for Level Set application:
    KRATOS_DEFINE_DOUBLE_VARIABLE( MIN_DT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( MAX_DT )
    KRATOS_DEFINE_DOUBLE_VARIABLE( VEL_ART_VISC )
    KRATOS_DEFINE_DOUBLE_VARIABLE( PR_ART_VISC )

//     //for Vulcan application
    KRATOS_DEFINE_DOUBLE_VARIABLE( LATENT_HEAT )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( SOLID_TEMPERATURE )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( FLUID_TEMPERATURE )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( AVERAGE_TEMPERATURE )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( INLET_TEMPERATURE)
     KRATOS_DEFINE_DOUBLE_VARIABLE( AMBIENT_TEMPERATURE )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( COUNTER )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( DISTANCE_CORRECTION )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( COMPUTED_DISTANCE )
//     KRATOS_DEFINE_DOUBLE_VARIABLE( MATERIAL )
//   KRATOS_DEFINE_DOUBLE_VARIABLE( MOULD_AVERAGE_TEMPERATURE)


    //vectors

    //for General kratos application:
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ROTATION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DELTA_ROTATION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( TORQUE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_VELOCITY )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_ACCELERATION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN_RATE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( REACTION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VELOCITY )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION )

    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( VOLUME_ACCELERATION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENT )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FACE_LOAD )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NORMAL )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( BODY_FORCE )

    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE_RESIDUAL )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENT_RESIDUAL )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( INTERNAL_FORCE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( EXTERNAL_FORCE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( CONTACT_FORCE )

    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LINEAR_MOMENTUM )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_MOMENTUM )

    KRATOS_DEFINE_VARIABLE( Vector, MARKER_LABELS )
    KRATOS_DEFINE_VARIABLE( Vector, MARKER_MESHES )

    KRATOS_DEFINE_VARIABLE( Vector, CONSTRAINT_LABELS )
    KRATOS_DEFINE_VARIABLE( Vector, CONSTRAINT_MESHES )

    KRATOS_DEFINE_VARIABLE( Vector, LOAD_LABELS )
    KRATOS_DEFINE_VARIABLE( Vector, LOAD_MESHES )

    //for Structural application:
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )

    KRATOS_DEFINE_VARIABLE( Vector, ELEMENTAL_DISTANCES )
    KRATOS_DEFINE_VARIABLE( Vector, MATERIAL_PARAMETERS )
    KRATOS_DEFINE_VARIABLE( Vector, INTERNAL_VARIABLES )
    KRATOS_DEFINE_VARIABLE( Vector, INSITU_STRESS )

    KRATOS_DEFINE_VARIABLE( Vector, PENALTY )
    KRATOS_DEFINE_VARIABLE( Vector, NORMAL_STRESS )
    KRATOS_DEFINE_VARIABLE( Vector, TANGENTIAL_STRESS )
    KRATOS_DEFINE_VARIABLE( Vector, STRESSES )
    KRATOS_DEFINE_VARIABLE( Vector, STRAIN )

    KRATOS_DEFINE_VARIABLE( vector<int>, NEIGHBOURS_INDICES )

    //ALE Application
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DETERMINANT )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ELEMENTSHAPE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MESH_VELOCITY )

    //for PFEM fluids application:
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( GRAVITY )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( NORMAL_TO_WALL )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( STRUCTURE_VELOCITY )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DRAG_FORCE )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( EMBEDDED_VELOCITY )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FRACT_VEL )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( ROTATION_CENTER )

    //for Other applications:
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( SEEPAGE_DRAG )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MASS )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( RHS )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( FORCE_CM )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_CM )

    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( DIRECTION )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS( Y )


    KRATOS_DEFINE_VARIABLE( Vector, BDF_COEFFICIENTS )

    //for Vulcan application
    KRATOS_DEFINE_VARIABLE( Vector, ENRICHED_PRESSURES )

    //matrices

    //for General kratos application:
    KRATOS_DEFINE_VARIABLE( Matrix, GREEN_LAGRANGE_STRAIN_TENSOR )
    KRATOS_DEFINE_VARIABLE( Matrix, PK2_STRESS_TENSOR )
    KRATOS_DEFINE_VARIABLE( Matrix, CAUCHY_STRESS_TENSOR )
//    KRATOS_DEFINE_VARIABLE( Matrix, LOCAL_INERTIA )
    KRATOS_DEFINE_VARIABLE( Matrix, LOCAL_CONSTITUTIVE_MATRIX )

    //for Structural application:
    KRATOS_DEFINE_VARIABLE( Matrix, INERTIA )

    //for General kratos application:
    //KRATOS_DEFINE_VARIABLE( ConstitutiveLaw::Pointer, CONSTITUTIVE_LAW )


    //for Structural application:
    //KRATOS_DEFINE_VARIABLE( WeakPointerVector< GeometricalObject >, NEIGHBOUR_EMBEDDED_FACES )
    //KRATOS_DEFINE_VARIABLE( ConvectionDiffusionSettings::Pointer,  CONVECTION_DIFFUSION_SETTINGS )
    //KRATOS_DEFINE_VARIABLE( RadiationSettings::Pointer,  RADIATION_SETTINGS )

    KRATOS_DEFINE_VARIABLE( PeriodicVariablesContainer, PERIODIC_VARIABLES )

    // Variables that should be moved to applications (but have too many dependencies)
    KRATOS_DEFINE_VARIABLE(int, FRACTIONAL_STEP )
    KRATOS_DEFINE_DOUBLE_VARIABLE( EQ_STRAIN_RATE )
    KRATOS_DEFINE_DOUBLE_VARIABLE( POWER_LAW_N )
    KRATOS_DEFINE_DOUBLE_VARIABLE( POWER_LAW_K )
    KRATOS_DEFINE_DOUBLE_VARIABLE( YIELD_STRESS )

    // Variables with general names that can be used across applications
    KRATOS_DEFINE_DOUBLE_VARIABLE( MU )
    KRATOS_DEFINE_DOUBLE_VARIABLE( TAU )
    KRATOS_DEFINE_DOUBLE_VARIABLE( ALPHA )

    KRATOS_DEFINE_DOUBLE_VARIABLE( SEARCH_RADIUS )

    KRATOS_DEFINE_3D_COMPLEX_VARIABLE_WITH_COMPONENTS( COMPLEX_DISPLACEMENT )
    KRATOS_DEFINE_3D_COMPLEX_VARIABLE_WITH_COMPONENTS( COMPLEX_REACTION )
    KRATOS_DEFINE_3D_COMPLEX_VARIABLE_WITH_COMPONENTS( COMPLEX_VELOCITY )
    KRATOS_DEFINE_3D_COMPLEX_VARIABLE_WITH_COMPONENTS( COMPLEX_ACCELERATION )

}  // namespace Kratos.

#undef  KRATOS_EXPORT_MACRO
#define KRATOS_EXPORT_MACRO KRATOS_NO_EXPORT

#endif // KRATOS_VARIABLES_H_INCLUDED  defined
