// Kratos Multi-Physics
//
// Copyright (c) 2016 Pooyan Dadvand, Riccardo Rossi, CIMNE (International Center for Numerical Methods in Engineering)
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
//
//  -   Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
//  -   Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer
//      in the documentation and/or other materials provided with the distribution.
//  -   All advertising materials mentioning features or use of this software must display the following acknowledgement:
//          This product includes Kratos Multi-Physics technology.
//  -   Neither the name of the CIMNE nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// HOLDERS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED ANDON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
// THE USE OF THISSOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.



// System includes

// External includes

// Project includes
#include "includes/define_python.h"
#include "includes/ublas_interface.h"
#include "includes/constitutive_law.h"
#include "includes/variables.h"
#include "python/add_variables_to_python.h"

namespace Kratos
{

namespace Python
{

using namespace boost::python;

void  AddVariablesToPython()
{
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DOMAIN_SIZE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POWER_LAW_N)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POWER_LAW_K)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EQ_STRAIN_RATE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YIELD_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MU )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TAU )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ALPHA )
    // KRATOS_REGISTER_IN_PYTHON_VARIABLE( KAPPA ) // in c2c_variables.h


    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTRAINT_LABELS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOAD_LABELS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MARKER_LABELS )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONSTRAINT_MESHES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOAD_MESHES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MARKER_MESHES )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOCAL_COORDINATES_SYSTEM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LOCAL_TANGENTIAL_VECTOR_1 )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LOCAL_TANGENTIAL_VECTOR_2 )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LOCAL_NORMAL_VECTOR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ELEMENTAL_DISTANCES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NL_ITERATION_NUMBER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRACTIONAL_STEP )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TIME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TIME_STEPS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( START_TIME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( END_TIME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DELTA_TIME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RESIDUAL_NORM )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONVERGENCE_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TEMPERATURE_OLD_IT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY_AIR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VISCOSITY_WATER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ERROR_RATIO )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( VELOCITY_LAPLACIAN_RATE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DISPLACEMENT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ROTATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DELTA_ROTATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( TORQUE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( REACTION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( BODY_FORCE )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( FORCE_RESIDUAL )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MOMENT_RESIDUAL )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( INTERNAL_FORCE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( EXTERNAL_FORCE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( CONTACT_FORCE )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LINEAR_MOMENTUM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ANGULAR_MOMENTUM )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( VOLUME_ACCELERATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( SEEPAGE_DRAG )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( NORMAL )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( FORCE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MOMENT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( FORCE_CM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM_CM )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MOMENTUM )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MASS )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( RHS )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( REACTION_WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( REACTION_AIR_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RHS_WATER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RHS_AIR )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WEIGHT_FATHER_NODES )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INTERNAL_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRAIN_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXTERNAL_ENERGY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( KINETIC_ENERGY )

//    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOCAL_INERTIA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOCAL_CONSTITUTIVE_MATRIX )

    //for structural application
    KRATOS_REGISTER_IN_PYTHON_CONSTITUTIVE_LAW_VARIABLE( CONSTITUTIVE_LAW )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INTERNAL_VARIABLES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MATERIAL_PARAMETERS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( GREEN_LAGRANGE_STRAIN_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PK2_STRESS_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CAUCHY_STRESS_TENSOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( YOUNG_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POISSON_RATIO )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( THICKNESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NEGATIVE_FACE_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POSITIVE_FACE_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( POROSITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DIAMETER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LIN_DARCY_COEF )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NONLIN_DARCY_COEF )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DRAG_FORCE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( STRUCTURE_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( K0 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_VOLUME )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STATIONARY )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FLAG_VARIABLE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DISTANCE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INERTIA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PERIODIC_PAIR_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PARTITION_INDEX )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( LAGRANGE_DISPLACEMENT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_AIR_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_WATER_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INTERNAL_FRICTION_ANGLE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAGRANGE_DISPLACEMENT )



    // for MultiScale application
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_STRAIN )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( COEFFICIENT_THERMAL_EXPANSION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CHARACTERISTIC_LENGTH_MULTIPLIER )

    //for Incompressible Fluid application
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(FRACT_VEL)

    //for ALE application
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DETERMINANT )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ELEMENTSHAPE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( MESH_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AUX_MESH_VAR )

    //for AdjointFluidApplication
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ADJOINT_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ADJOINT_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( PRIMAL_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PRIMAL_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( SHAPE_SENSITIVITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_SENSITIVITY )

    //for electric application

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PARTITION_MASK )

    //for PFEM application TO BE REMOVED
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_AREA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_H )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( NORMAL_TO_WALL )
    //KRATOS_REGISTER_IN_PYTHON_VARIABLE(NEIGHBOUR_NODES)
    //KRATOS_REGISTER_IN_PYTHON_VARIABLE(NEIGHBOUR_ELEMENTS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRICTION_COEFFICIENT )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( BULK_MODULUS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SATURATION )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( GRAVITY )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( FACE_LOAD )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY_WATER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DENSITY_AIR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_ENTRY_VALUE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIRST_SATURATION_PARAM )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SECOND_SATURATION_PARAM )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PERMEABILITY_WATER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PERMEABILITY_AIR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( BULK_AIR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SCALE )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TEMP_CONV_PROJ )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CONVECTION_COEFFICIENT)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INSITU_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRESSES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STRAIN )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NODAL_MASS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AUX_INDEX )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( EXTERNAL_PRESSURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( BDF_COEFFICIENTS )
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( ROTATION_CENTER )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VELOCITY_PERIOD )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ANGULAR_VELOCITY_PERIOD )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( IDENTIFIER )


    //for xfem application
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CRACK_OPENING )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CRACK_TRANSLATION )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(ARRHENIUS)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(ARRHENIUSAUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(ARRHENIUSAUX_)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(PRESSUREAUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(NODAL_MAUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(NODAL_PAUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(FACE_HEAT_FLUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(HEAT_FLUX)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(TC)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(CONDUCTIVITY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(SPECIFIC_HEAT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(MATERIAL_VARIABLE)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(FUEL)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YO)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YF)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YI)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(Y1)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(Y2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YP)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(EMISSIVITY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(ENTHALPY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(MIXTURE_FRACTION)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YCH4)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YO2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YCO2)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YH2O)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(YN2)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(INCIDENT_RADIATION_FUNCTION)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE(ABSORPTION_COEFFICIENT)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(STEFAN_BOLTZMANN_CONSTANT)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS( DIRECTION )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(NODAL_SWITCH)
    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(Y)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SWITCH_TEMPERATURE )

    KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS(EMBEDDED_VELOCITY)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( REFINEMENT_LEVEL )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_SOUND_VELOCITY )

    // for Vulcan application
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LATENT_HEAT)

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ENRICHED_PRESSURES )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( INITIAL_PENALTY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_EPSILON )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_ALPHA1 )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( DP_K )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LAMBDA )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MIN_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MAX_DT )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WET_VOLUME)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( CUTTED_AREA)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NET_INPUT_MATERIAL)
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( MIU )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_CONTACT_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TANGENTIAL_CONTACT_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( STABILIZATION_FACTOR )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( AIR_SOUND_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( WATER_SOUND_VELOCITY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( ACTIVATION_LEVEL )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FIRST_TIME_STEP )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( QUASI_STATIC_ANALYSIS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( FRACTIONAL_STEP )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( LOAD_RESTART )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( RIGID_BODY_ID )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( NORMAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( TANGENTIAL_STRESS )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PENALTY )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE(  AMBIENT_TEMPERATURE )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( VEL_ART_VISC )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( PR_ART_VISC )
    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SOUND_VELOCITY )

    KRATOS_REGISTER_IN_PYTHON_VARIABLE( SEARCH_RADIUS )
}

}  // namespace Python.

} // Namespace Kratos
