//    |  /           |
//    ' /   __| _` | __|  _ \   __|
//    . \  |   (   | |   (   |\__ `
//   _|\_\_|  \__,_|\__|\___/ ____/
//                   Multi-Physics
//
//  License:		 BSD License
//					 Kratos default license: kratos/license.txt
//
//  Main authors:    Pooyan Dadvand
//


// System includes

// External includes

// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "includes/node.h"
#include "includes/element.h"
#include "includes/condition.h"
#include "includes/constitutive_law.h"
#include "includes/geometrical_object.h"

#include "includes/deprecated_variables.h"
#include "includes/convection_diffusion_settings.h"
#include "includes/radiation_settings.h"

namespace Kratos
{

//Create Variables by type:

//bools
KRATOS_CREATE_VARIABLE(bool, COMPUTE_LUMPED_MASS_MATRIX)

//for Structural application:

//for Level Set application:

//ints
KRATOS_CREATE_VARIABLE(int, DOMAIN_SIZE)

//for General kratos application:
KRATOS_CREATE_VARIABLE(int, LOAD_RESTART)
KRATOS_CREATE_VARIABLE(int, TIME_STEPS)
KRATOS_CREATE_VARIABLE(int, RIGID_BODY_ID)

//for Structural application
KRATOS_CREATE_VARIABLE(int, FIRST_TIME_STEP)
KRATOS_CREATE_VARIABLE(int, QUASI_STATIC_ANALYSIS)

KRATOS_CREATE_VARIABLE(int, NL_ITERATION_NUMBER)
KRATOS_CREATE_VARIABLE(int, PERIODIC_PAIR_INDEX)
KRATOS_CREATE_VARIABLE(int, STATIONARY)
KRATOS_CREATE_VARIABLE(int, ACTIVATION_LEVEL)

//for PFEM fluids application:
KRATOS_CREATE_VARIABLE(int, SCALE)

//for Level Set application:
KRATOS_CREATE_VARIABLE(int, REFINEMENT_LEVEL)

KRATOS_CREATE_VARIABLE(int, STEP)

//doubles

//for General kratos application:
KRATOS_CREATE_DOUBLE_VARIABLE(TIME)
KRATOS_CREATE_DOUBLE_VARIABLE(START_TIME)
KRATOS_CREATE_DOUBLE_VARIABLE(END_TIME)
KRATOS_CREATE_DOUBLE_VARIABLE(DELTA_TIME)

KRATOS_CREATE_DOUBLE_VARIABLE(RESIDUAL_NORM)
KRATOS_CREATE_DOUBLE_VARIABLE(CONVERGENCE_RATIO)

KRATOS_CREATE_DOUBLE_VARIABLE(TEMPERATURE)
KRATOS_CREATE_DOUBLE_VARIABLE(PRESSURE)

KRATOS_CREATE_DOUBLE_VARIABLE(NEGATIVE_FACE_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(POSITIVE_FACE_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(FACE_HEAT_FLUX)

KRATOS_CREATE_DOUBLE_VARIABLE(DENSITY)
KRATOS_CREATE_DOUBLE_VARIABLE(YOUNG_MODULUS)
KRATOS_CREATE_DOUBLE_VARIABLE(POISSON_RATIO)
KRATOS_CREATE_DOUBLE_VARIABLE(THICKNESS)

KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_H)

KRATOS_CREATE_DOUBLE_VARIABLE(KINETIC_ENERGY)
KRATOS_CREATE_DOUBLE_VARIABLE(INTERNAL_ENERGY)
KRATOS_CREATE_DOUBLE_VARIABLE(STRAIN_ENERGY)
KRATOS_CREATE_DOUBLE_VARIABLE(EXTERNAL_ENERGY)

KRATOS_CREATE_DOUBLE_VARIABLE(STABILIZATION_FACTOR)

KRATOS_CREATE_DOUBLE_VARIABLE(TIME_INTEGRATION_THETA)

//scheme info :: pass to elements
KRATOS_CREATE_DOUBLE_VARIABLE(NEWMARK_BETA)
KRATOS_CREATE_DOUBLE_VARIABLE(NEWMARK_GAMMA)
KRATOS_CREATE_DOUBLE_VARIABLE(BOSSAK_ALPHA)
KRATOS_CREATE_DOUBLE_VARIABLE(EQUILIBRIUM_POINT)

//for Structural application
KRATOS_CREATE_DOUBLE_VARIABLE(FRICTION_COEFFICIENT)
KRATOS_CREATE_DOUBLE_VARIABLE(LAMBDA)
KRATOS_CREATE_DOUBLE_VARIABLE(MIU)
KRATOS_CREATE_DOUBLE_VARIABLE(NORMAL_CONTACT_STRESS)
KRATOS_CREATE_DOUBLE_VARIABLE(TANGENTIAL_CONTACT_STRESS)

KRATOS_CREATE_VARIABLE(int,    PARTITION_INDEX)
KRATOS_CREATE_DOUBLE_VARIABLE(TEMPERATURE_OLD_IT)
KRATOS_CREATE_DOUBLE_VARIABLE(VISCOSITY)
KRATOS_CREATE_DOUBLE_VARIABLE(ERROR_RATIO)
KRATOS_CREATE_DOUBLE_VARIABLE(RHS_WATER)
KRATOS_CREATE_DOUBLE_VARIABLE(RHS_AIR)
KRATOS_CREATE_DOUBLE_VARIABLE(WEIGHT_FATHER_NODES)
KRATOS_CREATE_DOUBLE_VARIABLE(INITIAL_PENALTY)
KRATOS_CREATE_DOUBLE_VARIABLE(DP_EPSILON)
KRATOS_CREATE_DOUBLE_VARIABLE(DP_ALPHA1)
KRATOS_CREATE_DOUBLE_VARIABLE(DP_K)
KRATOS_CREATE_DOUBLE_VARIABLE(INTERNAL_FRICTION_ANGLE)
KRATOS_CREATE_DOUBLE_VARIABLE(K0)
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_VOLUME)

KRATOS_CREATE_DOUBLE_VARIABLE(WATER_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(REACTION_WATER_PRESSURE)

KRATOS_CREATE_DOUBLE_VARIABLE(AIR_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(REACTION_AIR_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(FLAG_VARIABLE)
KRATOS_CREATE_DOUBLE_VARIABLE(DISTANCE)

KRATOS_CREATE_DOUBLE_VARIABLE(LAGRANGE_AIR_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(LAGRANGE_WATER_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(LAGRANGE_TEMPERATURE)

// for MultiScale application
KRATOS_CREATE_VARIABLE(Vector, INITIAL_STRAIN)
KRATOS_CREATE_DOUBLE_VARIABLE(COEFFICIENT_THERMAL_EXPANSION)
KRATOS_CREATE_DOUBLE_VARIABLE(CHARACTERISTIC_LENGTH_MULTIPLIER)
//MeshMovingApplication
KRATOS_CREATE_DOUBLE_VARIABLE(AUX_MESH_VAR)

//AdjointFluidApplication
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ADJOINT_VELOCITY)
KRATOS_CREATE_DOUBLE_VARIABLE(ADJOINT_PRESSURE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(PRIMAL_VELOCITY)
KRATOS_CREATE_DOUBLE_VARIABLE(PRIMAL_PRESSURE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SHAPE_SENSITIVITY)
KRATOS_CREATE_DOUBLE_VARIABLE(NORMAL_SENSITIVITY)

//for Electric application


//for PFEM fluids application:
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_AREA)

KRATOS_CREATE_DOUBLE_VARIABLE(BULK_MODULUS)
KRATOS_CREATE_DOUBLE_VARIABLE(SATURATION)
KRATOS_CREATE_DOUBLE_VARIABLE(DENSITY_WATER)
KRATOS_CREATE_DOUBLE_VARIABLE(VISCOSITY_WATER)
KRATOS_CREATE_DOUBLE_VARIABLE(DENSITY_AIR)
KRATOS_CREATE_DOUBLE_VARIABLE(VISCOSITY_AIR)
KRATOS_CREATE_DOUBLE_VARIABLE(POROSITY)
KRATOS_CREATE_DOUBLE_VARIABLE(DIAMETER)
KRATOS_CREATE_DOUBLE_VARIABLE(LIN_DARCY_COEF)
KRATOS_CREATE_DOUBLE_VARIABLE(NONLIN_DARCY_COEF)

KRATOS_CREATE_DOUBLE_VARIABLE(AIR_ENTRY_VALUE)
KRATOS_CREATE_DOUBLE_VARIABLE(FIRST_SATURATION_PARAM)
KRATOS_CREATE_DOUBLE_VARIABLE(SECOND_SATURATION_PARAM)
KRATOS_CREATE_DOUBLE_VARIABLE(PERMEABILITY_WATER)
KRATOS_CREATE_DOUBLE_VARIABLE(PERMEABILITY_AIR)
KRATOS_CREATE_DOUBLE_VARIABLE(BULK_AIR)

KRATOS_CREATE_DOUBLE_VARIABLE(TEMP_CONV_PROJ)
KRATOS_CREATE_DOUBLE_VARIABLE(CONVECTION_COEFFICIENT)

KRATOS_CREATE_DOUBLE_VARIABLE(SOUND_VELOCITY)
KRATOS_CREATE_DOUBLE_VARIABLE(AIR_SOUND_VELOCITY)
KRATOS_CREATE_DOUBLE_VARIABLE(WATER_SOUND_VELOCITY)
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_MASS)
KRATOS_CREATE_DOUBLE_VARIABLE(AUX_INDEX)
KRATOS_CREATE_DOUBLE_VARIABLE(EXTERNAL_PRESSURE)
KRATOS_CREATE_DOUBLE_VARIABLE(VELOCITY_PERIOD)
KRATOS_CREATE_DOUBLE_VARIABLE(ANGULAR_VELOCITY_PERIOD)
KRATOS_CREATE_VARIABLE(std::string, IDENTIFIER)

//for Other applications:
KRATOS_CREATE_DOUBLE_VARIABLE(ARRHENIUS)
KRATOS_CREATE_DOUBLE_VARIABLE(ARRHENIUSAUX)
KRATOS_CREATE_DOUBLE_VARIABLE(ARRHENIUSAUX_)
KRATOS_CREATE_DOUBLE_VARIABLE(PRESSUREAUX)
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_MAUX)
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_PAUX)
KRATOS_CREATE_DOUBLE_VARIABLE(HEAT_FLUX)
KRATOS_CREATE_DOUBLE_VARIABLE(TC)
KRATOS_CREATE_DOUBLE_VARIABLE(CONDUCTIVITY)
KRATOS_CREATE_DOUBLE_VARIABLE(SPECIFIC_HEAT)
KRATOS_CREATE_DOUBLE_VARIABLE(MATERIAL_VARIABLE)
KRATOS_CREATE_DOUBLE_VARIABLE(FUEL)
KRATOS_CREATE_DOUBLE_VARIABLE(YO)
KRATOS_CREATE_DOUBLE_VARIABLE(YF)
KRATOS_CREATE_DOUBLE_VARIABLE(YI)
KRATOS_CREATE_DOUBLE_VARIABLE(Y1)
KRATOS_CREATE_DOUBLE_VARIABLE(Y2)
KRATOS_CREATE_DOUBLE_VARIABLE(YP)

KRATOS_CREATE_DOUBLE_VARIABLE(ABSORPTION_COEFFICIENT)
KRATOS_CREATE_DOUBLE_VARIABLE(STEFAN_BOLTZMANN_CONSTANT)

KRATOS_CREATE_DOUBLE_VARIABLE(EMISSIVITY)
KRATOS_CREATE_DOUBLE_VARIABLE(ENTHALPY)
KRATOS_CREATE_DOUBLE_VARIABLE(MIXTURE_FRACTION)

KRATOS_CREATE_DOUBLE_VARIABLE(YCH4)
KRATOS_CREATE_DOUBLE_VARIABLE(YO2)
KRATOS_CREATE_DOUBLE_VARIABLE(YCO2)
KRATOS_CREATE_DOUBLE_VARIABLE(YH2O)
KRATOS_CREATE_DOUBLE_VARIABLE(YN2)

KRATOS_CREATE_DOUBLE_VARIABLE(WET_VOLUME)
KRATOS_CREATE_DOUBLE_VARIABLE(CUTTED_AREA)
KRATOS_CREATE_DOUBLE_VARIABLE(NET_INPUT_MATERIAL)

KRATOS_CREATE_DOUBLE_VARIABLE(INCIDENT_RADIATION_FUNCTION)

KRATOS_CREATE_DOUBLE_VARIABLE(SWITCH_TEMPERATURE)
KRATOS_CREATE_DOUBLE_VARIABLE(NODAL_SWITCH)

//for Xfem application:
KRATOS_CREATE_DOUBLE_VARIABLE(CRACK_OPENING)
KRATOS_CREATE_DOUBLE_VARIABLE(CRACK_TRANSLATION)

//for Level Set application:
KRATOS_CREATE_DOUBLE_VARIABLE(MIN_DT)
KRATOS_CREATE_DOUBLE_VARIABLE(MAX_DT)
KRATOS_CREATE_DOUBLE_VARIABLE(VEL_ART_VISC)
KRATOS_CREATE_DOUBLE_VARIABLE(PR_ART_VISC)

//for Vulcan application
KRATOS_CREATE_DOUBLE_VARIABLE(LATENT_HEAT)
KRATOS_CREATE_DOUBLE_VARIABLE(AMBIENT_TEMPERATURE)


//vectors

//for General kratos application:
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ROTATION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DELTA_ROTATION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(TORQUE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_VELOCITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_ACCELERATION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_LAPLACIAN)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY_LAPLACIAN_RATE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DISPLACEMENT)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(REACTION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VELOCITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ACCELERATION)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(VOLUME_ACCELERATION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FORCE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENT)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FACE_LOAD)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NORMAL)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(BODY_FORCE)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FORCE_RESIDUAL)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENT_RESIDUAL)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(EXTERNAL_FORCE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(INTERNAL_FORCE)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(CONTACT_FORCE)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(LINEAR_MOMENTUM)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ANGULAR_MOMENTUM)

KRATOS_CREATE_VARIABLE(Vector, MARKER_LABELS)
KRATOS_CREATE_VARIABLE(Vector, MARKER_MESHES)

KRATOS_CREATE_VARIABLE(Vector, CONSTRAINT_LABELS)
KRATOS_CREATE_VARIABLE(Vector, CONSTRAINT_MESHES)

KRATOS_CREATE_VARIABLE(Vector, LOAD_LABELS)
KRATOS_CREATE_VARIABLE(Vector, LOAD_MESHES)

//for Structural application:
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(LAGRANGE_DISPLACEMENT)

KRATOS_CREATE_VARIABLE(Vector, ELEMENTAL_DISTANCES)
KRATOS_CREATE_VARIABLE(Vector, MATERIAL_PARAMETERS)
KRATOS_CREATE_VARIABLE(Vector, INTERNAL_VARIABLES)
KRATOS_CREATE_VECTOR_VARIABLE(INSITU_STRESS)

KRATOS_CREATE_VARIABLE(Vector, PENALTY)
KRATOS_CREATE_VARIABLE(Vector, NORMAL_STRESS)
KRATOS_CREATE_VARIABLE(Vector, TANGENTIAL_STRESS)
KRATOS_CREATE_VECTOR_VARIABLE(STRESSES)
KRATOS_CREATE_VECTOR_VARIABLE(STRAIN)

KRATOS_CREATE_VARIABLE(vector<int>, NEIGHBOURS_INDICES)

//ALE Application
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DETERMINANT)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ELEMENTSHAPE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MESH_VELOCITY)

//for PFEM fluids application:
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(GRAVITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(NORMAL_TO_WALL)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(STRUCTURE_VELOCITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DRAG_FORCE)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(EMBEDDED_VELOCITY)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FRACT_VEL)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(ROTATION_CENTER)

//for Other applications:
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(SEEPAGE_DRAG)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MASS)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(RHS)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(FORCE_CM)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(MOMENTUM_CM)

KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(DIRECTION)
KRATOS_CREATE_3D_VARIABLE_WITH_COMPONENTS(Y)

KRATOS_CREATE_VARIABLE(Vector, BDF_COEFFICIENTS)

//for Vulcan application
KRATOS_CREATE_VARIABLE(Vector, ENRICHED_PRESSURES)

//matrices

//for General kratos application:
KRATOS_CREATE_MATRIX_VARIABLE(GREEN_LAGRANGE_STRAIN_TENSOR)
KRATOS_CREATE_VARIABLE(Matrix, PK2_STRESS_TENSOR)
KRATOS_CREATE_MATRIX_VARIABLE(CAUCHY_STRESS_TENSOR)
//  KRATOS_CREATE_VARIABLE(Matrix, LOCAL_INERTIA)
KRATOS_CREATE_VARIABLE(Matrix, LOCAL_CONSTITUTIVE_MATRIX)

//for Structural application
KRATOS_CREATE_VARIABLE(Matrix, INERTIA)

//for General kratos application:
KRATOS_CREATE_CONSTITUTIVE_LAW_VARIABLE(CONSTITUTIVE_LAW)
//NEIGHBOUR_NODES defined in node.h
KRATOS_CREATE_VARIABLE(WeakPointerVector<Node<3> >, NEIGHBOUR_NODES)
//FATHER_NODES defined in node.h
KRATOS_CREATE_VARIABLE(WeakPointerVector<Node<3> >, FATHER_NODES)
//NEIGHBOR_ELEMENTS defined in element.h
KRATOS_CREATE_VARIABLE(WeakPointerVector<Element >, NEIGHBOUR_ELEMENTS)
//NEIGHBOR_CONDITIONS defined in condition.h
KRATOS_CREATE_VARIABLE(WeakPointerVector<Condition >, NEIGHBOUR_CONDITIONS)


//for Structural application:
KRATOS_CREATE_VARIABLE(WeakPointerVector< GeometricalObject<Node<3> > >, NEIGHBOUR_EMBEDDED_FACES)
KRATOS_CREATE_VARIABLE(ConvectionDiffusionSettings::Pointer,  CONVECTION_DIFFUSION_SETTINGS)
KRATOS_CREATE_VARIABLE(RadiationSettings::Pointer,  RADIATION_SETTINGS)


KRATOS_CREATE_VARIABLE(PeriodicVariablesContainer, PERIODIC_VARIABLES)

// Variables that should be moved to applications (but have too many dependencies)
KRATOS_CREATE_VARIABLE(int, FRACTIONAL_STEP)
KRATOS_CREATE_DOUBLE_VARIABLE(POWER_LAW_N)
KRATOS_CREATE_DOUBLE_VARIABLE(POWER_LAW_K)
KRATOS_CREATE_DOUBLE_VARIABLE(EQ_STRAIN_RATE)
KRATOS_CREATE_DOUBLE_VARIABLE(YIELD_STRESS)

// Variables with general names that can be used across applications
KRATOS_CREATE_DOUBLE_VARIABLE(MU)
KRATOS_CREATE_DOUBLE_VARIABLE(TAU)
KRATOS_CREATE_DOUBLE_VARIABLE(ALPHA)

KRATOS_CREATE_DOUBLE_VARIABLE(SEARCH_RADIUS)

}  // namespace Kratos.
